const colors = {
  light: {
    text: "#0f172a",
    tint: "#6366F1",
    background: "#F1F5F9",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#6366F1",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#334155",
    muted: "#eef1f8",
    mutedForeground: "#64748B",
    accent: "#22C55E",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22C55E",
    successForeground: "#ffffff",
    warning: "#F59E0B",
    warningForeground: "#ffffff",
    border: "#E2E8F0",
    input: "#E2E8F0",
  },
  dark: {
    text: "#0F172A",
    tint: "#6366F1",
    background: "#F5F7FB",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#6366F1",
    primaryForeground: "#ffffff",
    secondary: "#EEF2F7",
    secondaryForeground: "#334155",
    muted: "#E8EDF4",
    mutedForeground: "#64748B",
    accent: "#22C55E",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    success: "#22C55E",
    successForeground: "#ffffff",
    warning: "#F59E0B",
    warningForeground: "#0F172A",
    border: "#D7DEE8",
    input: "#D7DEE8",
  },
  radius: 16,
};

export default colors;
