import React from "react";
import type { StyleProp, TextStyle } from "react-native";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart2,
  Bell,
  BookOpen,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  Clock,
  Cloud,
  Copy,
  Cpu,
  Database,
  Edit2,
  Edit3,
  ExternalLink,
  Feather as FeatherIcon,
  FileText,
  Film,
  Folder,
  FolderPlus,
  Gift,
  Globe,
  HelpCircle,
  Hexagon,
  Home,
  Image as ImageIcon,
  Info,
  Layers,
  Loader,
  Lock,
  LogOut,
  Maximize2,
  MessageCircle,
  Minus,
  Moon,
  Octagon,
  Play,
  Plus,
  PlusCircle,
  Repeat,
  Search,
  Settings,
  Share2,
  Shield,
  SkipForward,
  Sliders,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  Video,
  X,
  XCircle,
  Zap,
  ZoomIn,
} from "lucide-react-native";

const ICONS: Record<string, React.ComponentType<{ size?: number; color?: string; strokeWidth?: number }>> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  award: Award,
  "bar-chart-2": BarChart2,
  bell: Bell,
  "book-open": BookOpen,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevrons-up": ChevronsUp,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "edit-2": Edit2,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  feather: FeatherIcon,
  "file-text": FileText,
  film: Film,
  folder: Folder,
  "folder-plus": FolderPlus,
  gift: Gift,
  globe: Globe,
  "help-circle": HelpCircle,
  hexagon: Hexagon,
  home: Home,
  image: ImageIcon,
  info: Info,
  layers: Layers,
  loader: Loader,
  lock: Lock,
  "log-out": LogOut,
  "maximize-2": Maximize2,
  "message-circle": MessageCircle,
  minus: Minus,
  moon: Moon,
  octagon: Octagon,
  play: Play,
  plus: Plus,
  "plus-circle": PlusCircle,
  repeat: Repeat,
  search: Search,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "skip-forward": SkipForward,
  sliders: Sliders,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  user: User,
  video: Video,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
  "zoom-in": ZoomIn,
};

export interface FeatherProps {
  name: string;
  size?: number;
  color?: string;
  style?: StyleProp<TextStyle>;
}

export function Feather({ name, size = 24, color = "#000" }: FeatherProps) {
  const Icon = ICONS[name] ?? Circle;
  return <Icon size={size} color={color} strokeWidth={2} />;
}

Feather.font = {} as Record<string, number>;
Feather.glyphMap = Object.fromEntries(
  Object.keys(ICONS).map((k) => [k, 0]),
) as Record<string, number>;

export default Feather;
